name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install TA-Lib system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make -j$(nproc)
          sudo make install
          cd ..
          rm -rf ta-lib/ ta-lib-0.4.0-src.tar.gz
          sudo mkdir -p /usr/local/lib
          sudo ln -sf /usr/lib/libta_lib.so* /usr/local/lib/
          echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/ta-lib.conf
          sudo ldconfig

      - name: Verify TA-Lib installation
        run: |
          ldconfig -p | grep ta_lib
          ls -l /usr/lib/libta_lib.so* /usr/local/lib/libta_lib.so*

      - name: Install Python dependencies
        run: |
          export TA_LIBRARY_PATH=/usr/lib
          export TA_INCLUDE_PATH=/usr/include
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: python --version