name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install TA-Lib system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..
          rm -rf ta-lib/ ta-lib-0.4.0-src.tar.gz
          echo "/usr/lib" | sudo tee -a /etc/ld.so.conf.d/ta-lib.conf
          sudo ldconfig
          sudo ln -s /usr/lib/libta_lib.so /usr/local/lib/libta_lib.so

      - name: Install Python dependencies
        run: |
          export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: python --version
